### PR TITLE
Graphics: Window Changes

### PR DESCRIPTION
**Pull request by ItsEasyActually**
This PR is in tandem with the SA Mod Manager branch https://github.com/X-Hax/SA-Mod-Manager/tree/dx-graphics-update. Please see https://github.com/X-Hax/SA-Mod-Manager/issues/11 for additional info on goals. Below is an outline of general changes, removals, and additions.

This has been tested pretty thoroughly, but I would appreciate additional testing to ensure all of the options and functionality work as intended. Please make sure, if you're testing this, to use that branch of the manager to have the correct settings.

### Primary Changes
- All window related code has been moved out of dllmain.cpp and into window.cpp and window.h.
- Fullscreen options have been modified to make use of the wrapper window to fix the Alt-Tab crash and to allow higher resolutions to be used without crashing the game. 
- Fullscreen now locks the cursor to the window (like standard Fullscreen options in apps). Borderless Fullscreen does not lock the cursor.
- WndProc_hook was rewritten to be a proper switch case statement in the event we want to update it in the future.
- A singular function called PatchWindow is now used for handling all of the changes. It's possible some additional stuff got included by accident.

### Removals
- Scale to Screen has been removed from the config options and is now turned on by default for Fullscreen, Borderless Fullscreen, and Custom Window. This makes it in line with how SA2's loader handles this option and alleviates potential confusion on end users who did not understand the option in the first place.
- Borderless has been removed as a dedicated check/bool option and is now set when the screen mode is Fullscreen, Borderless Fullscreen, or Custom Window. This was due to not being able to figure out how to decouple the reliance on borderless as a necessary option for some of the window management.

### Additions
- Show Cursor in Fullscreen as an option has been added. Original behavior was to just hide the cursor when in either Fullscreen mode. This option is disabled by default. 
---
The main goal of this was to work in tandem with the streamlined options introduced in the SA Mod Manager dx-graphics-update branch to make options easier for users to understand and utilize. It also seeks migrate some code out of dllmain.cpp for easier editing in the future. Unfortunately, most of this is just copy/paste with general changes where needed from dllmain.cpp. It does not make any major attempts to rewrite/streamline any of the code. 

That said, any suggestions on what to change or patch up is welcome, same goes for any help with this. This can't be merged until that SA Mod Manager branch is also ready to be merged as they both hinge on the changes being introduced. That thing is basically ready to go however (other than some variables cleanup), so it's just a matter of making sure this is ready to go.

### CODE REVIEW

**Comment by MainMemory** [comment]
You can't just add new fields into the middle of LoaderSettings, that breaks backwards compatibilityy.

**Comment by ItsEasyActually** [comment]
Ah thanks for the catch. Curious though, is it actually an issue with the move to json? Either way, I'll move the additions to the bottom.

**Comment by MainMemory** [comment]
Yes, because mods access these fields with their offset in bytes. If an old mod tries to read a setting from `LoaderSettings` and the struct that the mod loader is giving it doesn't match what it was when the mod was compiled, it'll read the wrong data. Also, make sure to increment `ModLoaderVer` any time you add new fields to anything contained in `HelperFunctions`, and mark which version the field was added in a comment.

**Comment by ItsEasyActually** [comment]
Gotcha, that makes sense.

In this case, since nothing was directly added to the HelperFunctions, would it be advised to just bump the version to 20 and comment the LoaderSettings' new variables?

**Comment by MainMemory** [comment]
Yes. It's also worth noting that if any settings are removed, it's best to leave the field in the struct and set an appropriate default value, tagging the field with `__declspec(deprecated)`.

**Pull request merged**
